name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build project
      run: |
        npm ci
        npm run build-prod
    - name: Run tests
      run:  npm test
    - name: Lint code
      run: npm run lint
      env:
        CI: true
